[package]
name = "chess"
version = "0.1.0"
edition = "2021"
# build = "build.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chess_board = { path = "../chess_board" }
move_generator = { path = "../move_generator" }
bevy = "0.13.0"
bevy_wasm_window_resize = "0.3.0"
