/* tslint:disable */
/* eslint-disable */
export const main: (a: number, b: number) => number;
export const __wbg_wbg_rayon_poolbuilder_free: (a: number, b: number) => void;
export const initThreadPool: (a: number) => number;
export const wbg_rayon_poolbuilder_build: (a: number) => void;
export const wbg_rayon_poolbuilder_mainJS: (a: number) => number;
export const wbg_rayon_poolbuilder_numThreads: (a: number) => number;
export const wbg_rayon_poolbuilder_receiver: (a: number) => number;
export const wbg_rayon_start_worker: (a: number) => void;
export const __wasm_bindgen_func_elem_143770: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_135668: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_142570: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_9826: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_138230: (a: number, b: number, c: number, d: number) => void;
export const __wasm_bindgen_func_elem_137523: (a: number, b: number, c: number, d: number) => void;
export const __wasm_bindgen_func_elem_137523_14: (a: number, b: number, c: number, d: number) => void;
export const __wasm_bindgen_func_elem_11178: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_11178_3: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_11178_4: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_11178_5: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_11178_6: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_11178_7: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_11178_8: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_11178_9: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_11178_10: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_147840: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_142571: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_135669: (a: number, b: number) => void;
export const memory: WebAssembly.Memory;
export const __wbindgen_export: (a: number, b: number) => number;
export const __wbindgen_export2: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export3: (a: number) => void;
export const __wbindgen_export4: (a: number, b: number, c: number) => void;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
export const __wbindgen_thread_destroy: (a?: number, b?: number, c?: number) => void;
export const __wbindgen_start: (a: number) => void;
